### ISSUE TITLE
Travis gets stuck on `MakerAdminTest._wait_for_startup`

### ISSUE THREAD

**Issue by emanuelen5** [makerspace/makeradmin#17]
For some reason Travis seems to often get stuck waiting for the services to be brought up. 

## Travis output
```travis_output

[...]

Recreating test_rfid_1
Recreating test_membership_1
ail-dispatcher_1 ... 
Recreating test_email-dispatcher_1
E
======================================================================
ERROR: setUpClass (tests.MakerAdminTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/makerspace/makeradmin/tests.py", line 128, in setUpClass
    MakerAdminTest._wait_for_startup()
  File "/home/travis/build/makerspace/makeradmin/tests.py", line 76, in _wait_for_startup
    raise Exception("Timeout while waiting for services to start")
Exception: Timeout while waiting for services to start
----------------------------------------------------------------------
Ran 0 tests in 91.629s
FAILED (errors=1)
make: *** [test] Error 1
The command "make test" exited with 2.
Done. Your build exited with 1.
```

## SLOC
https://github.com/makerspace/makeradmin/blob/f8af5cae3d79e21a26d1aa777328deba2c15487b/tests.py#L61-L74

**Comment by HalfVoxel** [comment]
Also happens locally sometimes. Not quite sure what is causing it.

**Comment by emanuelen5** [comment]
@andersroos claims to have solved this

**Comment by HalfVoxel** [comment]
Oh. Where?

**Comment by andersroos** [comment]
Ehh, did not claim that, said it may have been solved when i solved another problem. But that one was not intermittent.
