### ISSUE TITLE
Accessy causes internal server errors in the admin UI if no accessy key has been set

### ISSUE THREAD

**Issue by HalfVoxel** [makerspace/makeradmin#313]
![image](https://github.com/makerspace/makeradmin/assets/1144597/230576de-4b92-45ad-a0e5-5fc2f8778e08)

```
makeradmin-api-1               | [2023-08-13 08:03:52 +0000] [8] [DEBUG] GET /membership/member/4163/access
makeradmin-api-1               | 2023-08-13 08:03:52,109 INFO [8/MainThread /work/src/multiaccessy/accessy.py:248]: NO ACCESSY SESSION TOKEN (ID or CLIENT not configured), skipping get from path='/org/admin/organization/None/invitation'
makeradmin-api-1               | 2023-08-13 08:03:52,109 INFO [8/MainThread /work/src/multiaccessy/accessy.py:248]: NO ACCESSY SESSION TOKEN (ID or CLIENT not configured), skipping get from path='/asset/admin/organization/None/user?page_number=0&page_size=10000'
makeradmin-api-1               | 2023-08-13 08:03:52,109 ERROR [8/MainThread /usr/local/lib/python3.11/site-packages/flask/app.py:1414]: Exception on /membership/member/4163/access [GET]
makeradmin-api-1               | Traceback (most recent call last):
makeradmin-api-1               |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
makeradmin-api-1               |     response = self.full_dispatch_request()
makeradmin-api-1               |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
makeradmin-api-1               |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
makeradmin-api-1               |     rv = self.handle_user_exception(e)
makeradmin-api-1               |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
makeradmin-api-1               |   File "/usr/local/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
makeradmin-api-1               |     return cors_after_request(app.make_response(f(*args, **kwargs)))
makeradmin-api-1               |                                                 ^^^^^^^^^^^^^^^^^^
makeradmin-api-1               |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
makeradmin-api-1               |     rv = self.dispatch_request()
makeradmin-api-1               |          ^^^^^^^^^^^^^^^^^^^^^^^
makeradmin-api-1               |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
makeradmin-api-1               |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
makeradmin-api-1               |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
makeradmin-api-1               |   File "/work/src/service/internal_service.py", line 70, in view_wrapper
makeradmin-api-1               |     data = f(*args, **kwargs)
makeradmin-api-1               |            ^^^^^^^^^^^^^^^^^^
makeradmin-api-1               |   File "/work/src/membership/views.py", line 106, in member_get_access
makeradmin-api-1               |     return get_access_summary(entity_id)
makeradmin-api-1               |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
makeradmin-api-1               |   File "/work/src/membership/membership.py", line 197, in get_access_summary
makeradmin-api-1               |     groups = accessy_session.get_user_groups(msisdn)
makeradmin-api-1               |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
makeradmin-api-1               |   File "/work/src/multiaccessy/accessy.py", line 188, in get_user_groups
makeradmin-api-1               |     accessy_member = self._get_org_user_from_phone(phone_number)
makeradmin-api-1               |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
makeradmin-api-1               |   File "/work/src/multiaccessy/accessy.py", line 377, in _get_org_user_from_phone
makeradmin-api-1               |     users_in_org = self._get_users_org()
makeradmin-api-1               |                    ^^^^^^^^^^^^^^^^^^^^^
makeradmin-api-1               |   File "/work/src/multiaccessy/accessy.py", line 304, in _get_users_org
makeradmin-api-1               |     return self._get_json_paginated(f"/asset/admin/organization/{self.organization_id()}/user")
makeradmin-api-1               |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
makeradmin-api-1               |   File "/work/src/multiaccessy/accessy.py", line 279, in _get_json_paginated
makeradmin-api-1               |     current_items = data["items"]
makeradmin-api-1               |                     ~~~~^^^^^^^^^
makeradmin-api-1               | KeyError: 'items'
makeradmin-api-1               | 172.19.0.1 - - [13/Aug/2023:08:03:52 +0000] "GET /membership/member/4163/access HTTP/1.1" 500 54 "http://localhost:8009/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"
```

**Comment by emanuelen5** [comment]
See #306
