### ISSUE TITLE
Trouble setting up Stripe memberships

### ISSUE THREAD

**Issue by amrsoll** [makerspace/makeradmin#321]
I followed the readme in order to setup the stripe memberships but couldn't make it work. Provided are the jsons for the products I have set up in Stripe.

### Setup

I setup 2 stripe products.

I have provided API keys for Stripe in test mode and ran `stripe listen --forward-to http://localhost:8010/webshop/stripe_callback` which seems to work as it logs succesful `[200] POST` requests

<details>
<summary>makerspace membership (monthly)</summary>

```json
{
  "id": "prod_xxxxxxxxxxxxxx",
  "object": "product",
  "active": true,
  "attributes": [
  ],
  "created": 1696873780,
  "default_price": "price_1NzNaLE6Y802P9CaLtQlEAR4",
  "description": "The standard membership",
  "features": [
    {
      "name": "Access to the makerspace anytime"
    },
    {
      "name": "Participate in the activities of the makerspace"
    }
  ],
  "images": [
  ],
  "livemode": false,
  "metadata": {
    "subscription_type": "membership",
    "price_type": "recurring"
  },
  "name": "makerspace membership",
  "owning_merchant": "acct_1HdEIzE6Y802P9Ca",
  "owning_merchant_info": "acct_1HdEIzE6Y802P9Ca",
  "package_dimensions": null,
  "shippable": null,
  "skus": {
    "object": "list",
    "data": [
    ],
    "has_more": false,
    "total_count": 0,
    "url": "/v1/skus?product=prod_xxxxxxxxxxxxxx&active=true"
  },
  "statement_descriptor": null,
  "tax_code": null,
  "type": "service",
  "unit_label": null,
  "updated": 1696875819,
  "url": null,
  "user_hidden_in_lists": false
}
```

</details>

<details>
<summary>labaccess (free, yearly)</summary>

```json
{
  "id": "prod_yyyyyyyyyyyyyyJ",
  "object": "product",
  "active": true,
  "attributes": [
  ],
  "created": 1696874914,
  "default_price": "price_1NzNsdE6Y802P9Cad4eV62fG",
  "description": null,
  "features": [
  ],
  "images": [
  ],
  "livemode": false,
  "metadata": {
    "subscription_type": "labaccess",
    "price_type": "recurring"
  },
  "name": "labaccess",
  "owning_merchant": "acct_1HdEIzE6Y802P9Ca",
  "owning_merchant_info": "acct_1HdEIzE6Y802P9Ca",
  "package_dimensions": null,
  "shippable": null,
  "skus": {
    "object": "list",
    "data": [
    ],
    "has_more": false,
    "total_count": 0,
    "url": "/v1/skus?product=prod_yyyyyyyyyyyyyyJ&active=true"
  },
  "statement_descriptor": null,
  "tax_code": null,
  "type": "service",
  "unit_label": null,
  "updated": 1696876118,
  "url": null,
  "user_hidden_in_lists": false
}
```
</details>

### Bug

The api finds the makerspace membership `prod_xxxxxxxxxxxxxx` but for some reason:
- finds the associated `metadata->subscription_type=membership`
- doesn't find the associated `metadata->price_type=recurring`

<details>
<summary>Logs</summary>

```log
makeradmin-api-1               | [2023-10-09 18:43:00 +0000] [9] [DEBUG] GET /webshop/register_page_data
makeradmin-api-1               | 2023-10-09 18:43:00,793 INFO [9/MainThread /usr/local/lib/python3.11/site-packages/stripe/util.py:70]: message='Request to Stripe api' method=get path=https://api.stripe.com/v1/products/search?query=metadata[%27subscription_type%27]%3A%27membership%27
makeradmin-api-1               | 2023-10-09 18:43:01,182 INFO [9/MainThread /usr/local/lib/python3.11/site-packages/stripe/util.py:70]: message='Stripe API response' path=https://api.stripe.com/v1/products/search?query=metadata[%27subscription_type%27]%3A%27membership%27 response_code=200
makeradmin-api-1               | 2023-10-09 18:43:01,183 WARNING [9/MainThread /work/src/shop/stripe_subscriptions.py:363]: product found: {}
makeradmin-api-1               | 2023-10-09 18:43:01,184 INFO [9/MainThread /usr/local/lib/python3.11/site-packages/stripe/util.py:70]: message='Request to Stripe api' method=get path=https://api.stripe.com/v1/prices?product=prod_xxxxxxxxxxxxxx
makeradmin-api-1               | 2023-10-09 18:43:01,487 INFO [9/MainThread /usr/local/lib/python3.11/site-packages/stripe/util.py:70]: message='Stripe API response' path=https://api.stripe.com/v1/prices?product=prod_xxxxxxxxxxxxxx response_code=200
makeradmin-api-1               | 2023-10-09 18:43:01,488 ERROR [9/MainThread /usr/local/lib/python3.11/site-packages/flask/app.py:825]: Exception on /webshop/register_page_data [GET]
makeradmin-api-1               | Traceback (most recent call last):
makeradmin-api-1               |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
makeradmin-api-1               |     response = self.full_dispatch_request()
makeradmin-api-1               |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
makeradmin-api-1               |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
makeradmin-api-1               |     rv = self.handle_user_exception(e)
makeradmin-api-1               |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
makeradmin-api-1               |   File "/usr/local/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
makeradmin-api-1               |     return cors_after_request(app.make_response(f(*args, **kwargs)))
makeradmin-api-1               |                                                 ^^^^^^^^^^^^^^^^^^
makeradmin-api-1               |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
makeradmin-api-1               |     rv = self.dispatch_request()
makeradmin-api-1               |          ^^^^^^^^^^^^^^^^^^^^^^^
makeradmin-api-1               |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
makeradmin-api-1               |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
makeradmin-api-1               |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
makeradmin-api-1               |   File "/work/src/service/internal_service.py", line 70, in view_wrapper
makeradmin-api-1               |     data = f(*args, **kwargs)
makeradmin-api-1               |            ^^^^^^^^^^^^^^^^^^
makeradmin-api-1               |   File "/work/src/shop/views.py", line 241, in register_page_data
makeradmin-api-1               |     get_subscription_products()
makeradmin-api-1               |   File "/work/src/shop/stripe_subscriptions.py", line 190, in get_subscription_products
makeradmin-api-1               |     SubscriptionType.MEMBERSHIP: setup_subscription_makeradmin_product(SubscriptionType.MEMBERSHIP).id,
makeradmin-api-1               |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
makeradmin-api-1               |   File "/work/src/shop/stripe_subscriptions.py", line 116, in setup_subscription_makeradmin_product
makeradmin-api-1               |     subscription_prices = lookup_subscription_price_for(subscription_type)
makeradmin-api-1               |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
makeradmin-api-1               |   File "/work/src/shop/stripe_subscriptions.py", line 376, in lookup_subscription_price_for
makeradmin-api-1               |     len(recurring_prices) == 1
makeradmin-api-1               | AssertionError: Expected to find a single stripe price for MEMBERSHIP with metadata->price_type=recurring, but found 0 prices: []
makeradmin-api-1               | 172.18.0.1 - - [09/Oct/2023:18:43:01 +0000] "GET /webshop/register_page_data HTTP/1.1" 500 54 "http://localhost:8011/" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/117.0"
```

</details>

### Notes

From looking at the code, I assumed the frequency (monthly/yearly) of a subscription would not matter.

**Comment by amrsoll** [comment]
Could it be that the filters are actually looking at the metadata on the _Price_ and not the _Product_ itself?

```py
    prices = list(retry(lambda: stripe.Price.list(product=product.stripe_id)))
    # [ ... ] 
    recurring_prices = [
        p
        for p in prices
        if (MSMetaKeys.PRICE_TYPE.value in p["metadata"]) and (p["metadata"][MSMetaKeys.PRICE_TYPE.value] == PriceType.RECURRING.value)
    ]
```

**Comment by amrsoll** [comment]
Ooooh now I see, I think I misunderstood the README, thank yall for the rubber ducking :smile:
